/* Batch 19: +55 argue (empty talk, fraud shows, decay chains, self-inflicted ends). */

const BULK_ARGUE18 = [
["出言不逊","chū yán bù xùn",2,"Speaks with insolence — the mouth moves before the manners do.","他对服务员出言不逊被拍下。","说话傲慢无礼。","exit words not humble"],
["出口伤人","chū kǒu shāng rén",2,"The mouth opens, the wounds appear.","他说话从不考虑别人感受，出口伤人。","说出的话伤害别人。","exit mouth wound people"],
["祸从口出","huò cóng kǒu chū",2,"Disaster enters through the mouth.","他在酒桌上乱说话，祸从口出。","说话不谨慎给自己惹祸。","disaster from mouth exit"],
["大吹法螺","dà chuī fǎ luó",2,"Blows the giant conch of self-praise.","他大吹法螺说自己认识某某大佬。","比喻说大话。","big blow law conch"],
["吹牛拍马","chuī niú pāi mǎ",2,"Blows bulls and pats horses — flattery as a career path.","他靠吹牛拍马混进了管理层。","说大话巴结讨好别人。","blow bull pat horse"],
["曲意逢迎","qū yì féng yíng",2,"Bends his own will to please.","他对上司曲意逢迎。","违背本意去迎合别人。","bend will meet please"],
["卑鄙龌龊","bēi bǐ wò chuò",3,"Base and filthy — character at rock bottom.","他干的那些事卑鄙龌龊。","品质行为卑劣恶劣。","base mean filthy sordid"],
["污七八糟","wū qī bā zāo",2,"Filth in seven-eight shades of mess.","他屋里污七八糟什么都有。","形容混乱不堪。","filth seven eight mess"],
["乱七八糟","luàn qī bā zāo",2,"Mess in sevens and eights — nothing where it should be.","他房间乱七八糟。","混乱无序。","chaos seven eight mess"],
["杂乱无章","zá luàn wú zhāng",2,"Miscellaneous without any order.","他的笔记杂乱无章。","乱七八糟没有条理。","miscellaneous chaos no order"],
["一团漆黑","yī tuán qī hēi",2,"One solid blob of pitch-black — the future, the room, the policy.","停电后屋里一团漆黑。","形容一片黑暗。","one blob pitch black"],
["暗无天日","àn wú tiān rì",3,"No daylight reaches here — law and hope both absent.","旧监狱里暗无天日。","社会极端黑暗，不见一点光明。","dark no sky sun"],
["惨绝人寰","cǎn jué rén huán",3,"Cruelty unmatched in all the human world.","那场屠杀惨绝人寰。","悲惨到了人间没有的程度。","cruelty beyond human world"],
["触目惊心","chù mù jīng xīn",2,"What the eye meets, the heart shudders.","事故现场的惨状触目惊心。","看到严重情况心里震惊。","touch eye startle heart"],
["骇人听闻","hài rén tīng wén",2,"Shocking to hear — and the facts are worse.","虐童案骇人听闻。","使人听了非常震惊。","startle people hear news"],
["耸人听闻","sǒng rén tīng wén",2,"Deliberately shocking — exaggeration as headline.","标题耸人听闻只为流量。","故意说夸大惊奇的话。","shock people hear news"],
["危言耸听","wēi yán sǒng tīng",2,"Alarmist words designed to frighten.","别信他危言耸听。","故意说吓人的话使人吃惊。","fear words shock hearing"],
["陈词滥调","chén cí làn diào",2,"Stale words, worn-out tunes.","他的发言全是陈词滥调。","陈腐空泛的论调。","old words rotten tunes"],
["老生常谈","lǎo shēng cháng tán",2,"The old scholar's regular talk — true, but tired.","他讲的道理虽对，却是老生常谈。","平常的老话，没有新意。","old scholar often talks"],
["废话连篇","fèi huà lián piān",2,"Nonsense linked page after page.","他的报告废话连篇。","形容文章或讲话中废话太多。","waste words linked pages"],
["自我吹嘘","zì wǒ chuī xū",2,"Self-blowing self-inflating — achievements patented by the mouth.","他到处自我吹嘘。","比喻自我吹捧。","self self blow inflate"],
["沽名钓誉","gū míng diào yù",2,"Fishing for fame with fake bait.","他做慈善只为沽名钓誉。","用手段谋取名声和赞誉。","buy fame fish praise"],
["一面之词","yī miàn zhī cí",2,"One side of the story — never the whole truth.","判决不能只听一面之词。","单方面的话。","one side its words"],
["偏听偏信","piān tīng piān xìn",2,"Listening to one side, believing only that side.","他偏听偏信，冤枉了好人。","只听一方面的话就轻信。","biased listen biased believe"],
["以讹传讹","yǐ é chuán é",2,"The error spread, retelling the error.","谣言以讹传讹越传越离谱。","把本来就不正确的话又错误地传出去。","use error pass error"],
["三人成虎","sān rén chéng hǔ",3,"Three people speaking make a tiger — a lie told thrice becomes fact.","谣言重复三遍就成了三人成虎。","说的人多了就能误传为真。","three people become tiger"],
["积毁销骨","jī huǐ xiāo gǔ",3,"Accumulated slander melts the bones — gossip as slow acid.","流言积毁销骨，他被逼离开了公司。","毁谤积累足以致人毁灭。","gather slander melt bone"],
["人言可畏","rén yán kě wèi",2,"People's words are fearsome — gossip kills softly.","她被人言可畏的流言逼走了。","人们的流言蜚语是很可怕的。","people words fearsome dreadful"],
["招摇撞骗","zhāo yáo zhuàng piàn",2,"Parades around swindling — fake title, real victims.","他假扮军官招摇撞骗。","假借名义到处炫耀行骗。","parade swagger crash swindle"],
["坑蒙拐骗","kēng méng guǎi piàn",2,"Cheats, deceives, tricks, swindles — the full quartet.","他坑蒙拐骗无所不为。","用各种手段骗人。","trap deceive trick swindle"],
["招摇过市","zhāo yáo guò shì",2,"Struts through the market in full show.","他开着借来的豪车招摇过市。","大摇大摆地炫耀。","parade swagger cross market"],
["招兵买马","zhāo bīng mǎi mǎ",2,"Recruits soldiers, buys horses — assembling the scheme's crew.","他招兵买马准备大干一场。","组织或扩充力量。","recruit soldiers buy horses"],
["装点门面","zhuāng diǎn mén miàn",2,"Decorates the facade — substance stays absent.","他学外语只为装点门面。","只粉饰表面。","pretend decorate door face"],
["粉墨登场","fěn mò dēng chǎng",2,"Powers on the makeup, mounts the stage — villains performing proudly.","那些骗子又粉墨登场了。","坏人登上舞台表演（贬义）。","powder makeup mount stage"],
["尸位素餐","shī wèi sù cān",3,"Occupies the post, eats without serving.","他占着位子不干活，尸位素餐。","空占职位不做事白吃饭。","corpse position plain meal"],
["无所作为","wú suǒ zuò wéi",2,"Nothing attempted, nothing achieved.","他在任十年无所作为。","工作中不作出任何成绩。","nothing do nothing achieve"],
["得过且过","dé guò qiě guò",2,"Gets by, and only by.","他做事从来得过且过。","只要过得去就这样过下去。","get by and get by"],
["因循守旧","yīn xún shǒu jiù",2,"Follows old routines, guards old ways.","公司因循守旧错失了转型。","沿袭旧的一套不求改进。","follow routines guard old"],
["墨守成规","mò shǒu chéng guī",2,"Ink-bound to old rules — Mo-tzu's defender never improvises.","他墨守成规，拒绝一切新想法。","守着老规矩不肯改变。","ink guard old rules"],
["故步自封","gù bù zì fēng",2,"Self-sealed in old steps.","他故步自封，市场早被别人占了。","安于现状，不求进取。","old steps self seal"],
["抱残守缺","bào cán shǒu quē",2,"Hugs the broken, guards the missing.","他抱残守缺，不肯更新设备。","守着残缺陈旧的东西不放。","hug broken guard missing"],
["老调重弹","lǎo diào chóng tán",2,"The old tune retuned and replayed.","他的发言又是老调重弹。","把陈旧的观点重新搬出来。","old tune replay again"],
["积重难返","jī zhòng nán fǎn",2,"Long accumulated, hard to return — the mess is now the system.","问题积重难返。","长期形成的问题难以改变。","accumulated heavy hard return"],
["病入膏肓","bìng rù gāo huāng",3,"The illness reached the vital region — no doctor remains.","这家公司管理病入膏肓。","病到了无法医治的地步。","illness enters vital region"],
["回天乏术","huí tiān fá shù",2,"No technique left to turn back heaven.","医生回天乏术，病人去世了。","局势无法挽回。","return heaven lacking technique"],
["大势已去","dà shì yǐ qù",2,"The grand momentum has left.","敌军大势已去开始溃逃。","有利的形势已经丧失。","grand trend already gone"],
["气数已尽","qì shù yǐ jìn",3,"The allotted fate fully spent.","这个王朝气数已尽。","命数已到尽头。","fate count already spent"],
["自取灭亡","zì qǔ miè wáng",3,"Walks himself into extinction.","逆流而动无异于自取灭亡。","自己的行为导致自己的灭亡。","self take destroy perish"],
["自掘坟墓","zì jué fén mù",3,"Digs his own grave — shovel provided by his own decisions.","他贪腐就是在自掘坟墓。","自己的所作所为把自己葬送。","self dig grave tomb"],
["玩火自焚","wán huǒ zì fén",3,"Plays with fire, burns in it.","挑衅者终将玩火自焚。","干冒险或害人的勾当最后受害的还是自己。","play fire self burn"],
["作茧自缚","zuò jiǎn zì fù",2,"Spins the cocoon, binds himself — his own rules trap him.","他定的死规矩把自己也困住了，作茧自缚。","做了某事结果使自己受困。","spin cocoon self bind"],
["自讨没趣","zì tǎo méi qù",2,"Asks for embarrassment, gets a full serving.","他去演讲被嘘下台自讨没趣。","自找难堪。","self seek no fun"],
["自取其辱","zì qǔ qí rǔ",3,"Fetches his own humiliation — delivered by his own hands.","他当众卖弄反被嘲弄，自取其辱。","自己招来侮辱。","self fetch its humiliation"],
["自相矛盾","zì xiāng máo dùn",2,"His own spear against his own shield — the founding contradiction.","他前后说法自相矛盾。","言语行动前后抵触。","self against spear shield"],
["反复无常","fǎn fù wú cháng",2,"Reverses and reverses again — no policy survives a day.","他态度反复无常。","变化不定，来回改变。","repeat reverse no constancy"]
];

mergeBulk(BULK_ARGUE18, "argue");
