/* Batch 18: +50 argue (villains, decline, smug fools, schemes). */

const BULK_ARGUE17 = [
["惨无人道","cǎn wú rén dào",3,"Cruel beyond all humanity.","纳粹集中营惨无人道。","残酷得丧失了人道。","cruel no human way"],
["灭绝人性","miè jué rén xìng",3,"Humanity utterly extinguished.","活体实验灭绝人性。","完全丧失了人的理性与情感。","extinguish utterly human nature"],
["丧心病狂","sàng xīn bìng kuáng",3,"Heart lost, mind gone mad.","为骗保竟杀害亲人，丧心病狂。","丧失理智像发了疯一样。","lose heart sick mad"],
["丧尽天良","sàng jìn tiān liáng",3,"Heaven's conscience, entirely lost.","卖假奶粉的丧尽天良。","没有一点良心。","lose all heaven conscience"],
["伤天害理","shāng tiān hài lǐ",3,"Injures heaven, harms reason.","这种骗局伤天害理。","做事凶恶残忍灭绝天理。","injure heaven harm reason"],
["无恶不作","wú è bú zuò",3,"No evil left un-done.","这伙人无恶不作。","什么坏事都干。","no evil not do"],
["敲骨吸髓","qiāo gǔ xī suǐ",3,"Cracks the bones to suck the marrow — exploitation at maximum.","奸商对工人敲骨吸髓。","剥削压迫极其残酷。","crack bone suck marrow"],
["巧立名目","qiǎo lì míng mù",2,"Cleverly invents the fee names.","公司巧立名目乱收费。","变着法定出种种名目。","cleverly establish itemize names"],
["欲壑难填","yù hè nán tián",2,"The valley of desire can never be filled.","他贪得无厌欲壑难填。","欲望像深谷难以填满。","desire valley hard fill"],
["见钱眼开","jiàn qián yǎn kāi",2,"Sees money, eyes light up.","他见钱眼开什么都肯干。","见到钱财眼睛都睁大了。","see money eyes open"],
["利令智昏","lì lìng zhì hūn",2,"Profit orders the wisdom to shut down.","利令智昏，他连朋友都骗。","贪图私利使头脑发昏。","profit orders wisdom dim"],
["嫉贤妒能","jí xián dù néng",2,"Jealous of the worthy, envious of the able.","上司嫉贤妒能，能人都走了。","妒忌有德行有才能的人。","jealous worthy envy able"],
["睚眦必报","yá zì bì bào",2,"A glare gets repaid in full — revenge as hobby.","他睚眦必报得罪不起。","瞪一眼的小怨也要报复。","glare stare must repay"],
["造谣生事","zào yáo shēng shì",2,"Makes rumors to stir incidents.","他最爱造谣生事挑起矛盾。","制造谣言挑起事端。","make rumor breed trouble"],
["偷偷摸摸","tōu tōu mō mō",1,"Sneak, sneak, touch, touch — everything in secret.","他偷偷摸摸不知道在干什么。","瞒着人做事不敢让人知道。","sneak sneak touch touch"],
["贼眉鼠眼","zéi méi shǔ yǎn",2,"Thief brows, rat eyes — looks guilty by default.","他贼眉鼠眼地四处张望。","神情鬼鬼祟祟。","thief brows rat eyes"],
["獐头鼠目","zhāng tóu shǔ mù",2,"River-deer head, rat eyes — villainy written on the face.","那人獐头鼠目，一看就不可信。","相貌丑陋神情狡猾。","deer head rat eyes"],
["奴颜媚骨","nú yán mèi gǔ",3,"Slave face, fawning bones — spine sold permanently.","他对外国老板奴颜媚骨。","卑躬屈膝谄媚讨好的样子。","slave face fawn bones"],
["俯首帖耳","fǔ shǒu tiē ěr",2,"Head lowered, ears flattened — total submission.","他在上司面前俯首帖耳。","非常驯服恭顺。","lower head flatten ears"],
["摇尾乞怜","yáo wěi qǐ lián",2,"Wags the tail begging for pity.","他在领导面前摇尾乞怜。","像狗摇尾巴讨好人。","wag tail beg pity"],
["卖国求荣","mài guó qiú róng",3,"Sells the nation for personal glory.","汉奸卖国求荣遗臭万年。","出卖国家利益谋取个人富贵。","sell nation seek glory"],
["里应外合","lǐ yìng wài hé",2,"Answers inside, attacks outside — the gates open themselves.","小偷里应外合偷走了库房。","外面攻打里面接应。","inside answer outside join"],
["串通一气","chuàn tōng yī qì",2,"Colludes into one single breath.","供应商和验收员串通一气。","相互勾结一个鼻孔出气。","collude through one breath"],
["一丘之貉","yī qiū zhī hé",2,"Badgers of the same hill — equally worthless together.","他们俩是一丘之貉。","同为坏人彼此无差别。","one hill of badgers"],
["臭味相投","chòu wèi xiāng tóu",2,"Same foul smell, drawn together.","两人臭味相投结成团伙。","坏气味相互投合。","foul smell mutual attract"],
["狐群狗党","hú qún gǒu dǎng",2,"A pack of foxes, a gang of dogs.","他身边全是狐群狗党。","勾结在一起的坏人。","fox pack dog gang"],
["牛鬼蛇神","niú guǐ shé shén",2,"Ox ghosts and snake gods — every manner of bad element.","职场里的牛鬼蛇神他都见识过。","形形色色的坏人。","ox ghost snake god"],
["兴妖作怪","xīng yāo zuò guài",2,"Conjures demons to stir trouble.","有人在背后兴妖作怪。","挑起事端暗中破坏。","raise demon make trouble"],
["阴谋诡计","yīn móu guǐ jì",2,"Conspiracies and schemes — the full toolbox.","他满脑子阴谋诡计。","暗中的计谋和狡诈手段。","hidden schemes ghost tricks"],
["诡计多端","guǐ jì duō duān",2,"Tricks in every direction.","此人生性狡诈诡计多端。","狡诈的计谋特别多。","trick tricks many ends"],
["暗箭伤人","àn jiàn shāng rén",2,"Hidden arrow wounds the man — attacks from the dark.","他惯用暗箭伤人。","暗中用阴险手段伤人。","hidden arrow wound people"],
["指鸡骂狗","zhǐ jī mà gǒu",2,"Points at the chicken, curses the dog.","她指鸡骂狗地数落邻居。","表面骂这个实际骂那个。","point chicken curse dog"],
["借题发挥","jiè tí fā huī",2,"Borrows the topic, releases the attack.","他借题发挥把大家骂了一遍。","借某事为由发泄不满。","borrow topic release attack"],
["小题大做","xiǎo tí dà zuò",2,"Small topic, grand production.","一件小事非要开大会，小题大做。","把小事当大事处理。","small topic big production"],
["引火烧身","yǐn huǒ shāo shēn",2,"Lights the fire and stands in it.","他四处树敌引火烧身。","招来灾祸殃及自身。","invite fire burn self"],
["自讨苦吃","zì tǎo kǔ chī",2,"Asks for the bitterness, receives it.","放着好日子不过自讨苦吃。","自己给自己找麻烦。","self seek bitter eat"],
["自作自受","zì zuò zì shòu",2,"Self-made, self-suffered.","当初不听劝现在自作自受。","自己做的错事自己承受。","self do self suffer"],
["罪有应得","zuì yǒu yīng dé",2,"The punishment the crimes earned.","他落得如此下场罪有应得。","受到了应得的惩罚。","crime has deserved gain"],
["自作聪明","zì zuò cōng míng",2,"Self-appointed clever — broke it while fixing it.","他自作聪明改了设置系统全崩。","自以为聪明而乱作主张。","self act smart clever"],
["得意洋洋","dé yì yáng yáng",2,"Pride flowing in every direction.","他得意洋洋地展示奖杯。","非常得意的样子。","proud glad vast vast"],
["沾沾自喜","zhān zhān zì xǐ",2,"Smug over a smidgen of success.","考了第一就沾沾自喜。","自以为很好而得意。","smug smug self pleased"],
["自鸣得意","zì míng dé yì",2,"Sounds his own trumpet of satisfaction.","他自鸣得意地展示新手机。","自己表示很得意。","self ring achieve proud"],
["装模作样","zhuāng mú zuò yàng",2,"Poses the model, plays the manner.","他装模作样地翻了两页书。","故意做作故作姿态。","pretend model make manner"],
["装聋作哑","zhuāng lóng zuò yǎ",2,"Plays deaf and dumb — convenient silence.","问他话他装聋作哑。","故意不理睬装作不知道。","pretend deaf act mute"],
["装疯卖傻","zhuāng fēng mài shǎ",2,"Plays mad, sells silly — dodges work by acting.","一到干活他就装疯卖傻。","故意装疯卖傻逃避责任。","pretend mad sell silly"],
["造谣中伤","zào yáo zhòng shāng",2,"Makes rumors to wound people.","他造谣中伤前同事。","制造谣言攻击陷害别人。","make rumor strike wound"],
["万人唾骂","wàn rén tuò mà",3,"Spit upon by ten thousand.","这个贪官被万人唾骂。","被众人痛骂。","myriad people spit scold"],
["千夫所指","qiān fū suǒ zhǐ",3,"The pointing fingers of a thousand men.","叛徒落得千夫所指。","被众人所指责。","thousand men all point"],
["众矢之的","zhòng shǐ zhī dì",3,"The target of a thousand arrows — all blame lands here.","他成了大家批评的众矢之的。","大家攻击的目标。","crowd arrows of target"],
["财迷心窍","cái mí xīn qiào",2,"Money bewitches the mind's openings.","他财迷心窍连亲情都不顾。","被金钱迷住了心窍。","money bewitch mind openings"]
];

mergeBulk(BULK_ARGUE17, "argue");
