/* Batch 20 (FINAL): +45 argue (reversals, rage, rifts) — crosses the 500 line for every category. */

const BULK_ARGUE19 = [
["是非不分","shì fēi bù fēn",2,"Right and wrong, cannot tell apart.","他是非不分，帮坏人说话。","分不清对错好坏。","right wrong not tell"],
["不分皂白","bù fēn zào bái",2,"Without telling black from white.","他不分皂白就怪了我。","不分是非，不问缘由。","without telling black white"],
["一手包办","yī shǒu bāo bàn",2,"One hand packages everything — others get no say.","婚礼他一手包办，新人毫无发言权。","独自操纵，不让别人参与。","one hand package all"],
["独揽大权","dú lǎn dà quán",2,"Monopolizes all the grand power alone.","他在公司独揽大权。","独自掌握大权。","alone monopolize grand power"],
["滥用职权","làn yòng zhí quán",2,"Abuses the authority of the office.","他滥用职权给亲戚开绿灯。","过分地使用自己的职权。","abuse authority power office"],
["以权谋私","yǐ quán móu sī",2,"Uses power to plot private gain.","他利用职务以权谋私。","用手中的权力谋取私利。","using power plot gain"],
["权钱交易","quán qián jiāo yì",2,"Power-money deals behind closed doors.","查处了多起权钱交易。","用权换钱，用钱买权。","power money trade deals"],
["收受贿赂","shōu shòu huì lù",2,"Accepts bribes, takes kickbacks.","官员收受贿赂被双规。","收取贿赂。","accept bribes take kickbacks"],
["腐化堕落","fǔ huà duò luò",2,"Corrupted, decayed, fallen.","他进城之后腐化堕落。","思想行为变坏堕落。","corrupt decay fall degrade"],
["骄奢淫逸","jiāo shē yín yì",3,"Arrogant, extravagant, debauched, indulgent.","富家子弟骄奢淫逸败光了家产。","骄横奢侈，荒淫无度。","arrogant extravagant debauched indulgent"],
["纸醉金迷","zhǐ zuì jīn mí",2,"Paper drunk, gold dazzled — a life of glittering emptiness.","他在纸醉金迷的生活里越陷越深。","奢华糜烂的生活。","paper drunk gold dazzled"],
["灯红酒绿","dēng hóng jiǔ lǜ",2,"Red lamps, green wine — nightlife's neon swamp.","他天天泡在灯红酒绿里。","寻欢作乐的腐化生活。","lamps red wine green"],
["醉生梦死","zuì shēng mèng sǐ",2,"Drunk while living, dreaming while dying.","他浑浑噩噩醉生梦死。","像喝醉酒和做梦一样糊涂地活着。","drunk living dream dying"],
["浑浑噩噩","hún hún è è",2,"Muddled through, dazed along.","他浑浑噩噩地过了半辈子。","糊里糊涂地过日子。","muddled muddled dazed confused"],
["糊里糊涂","hú lǐ hú tú",1,"Befuddled inside, smeared all over.","他糊里糊涂地签了合同。","认识模糊，不明事理。","muddled inside muddled smeared"],
["一错再错","yī cuò zài cuò",2,"One mistake, then another on top.","他一错再错，最终无法挽回。","屡次犯错而不悔改。","one mistake then more"],
["将错就错","jiāng cuò jiù cuò",2,"Takes the wrong, accepts it — riding the mistake to the end.","名字写错了只好将错就错。","事情做错了索性顺着错下去。","take wrong accept it"],
["铸成大错","zhù chéng dà cuò",3,"Cast into a grand mistake — molten, permanent.","一时糊涂铸成大错。","造成重大的错误。","cast into grand mistake"],
["大错特错","dà cuò tè cuò",3,"Big wrong, especially wrong.","你这样想就大错特错了。","完全错了。","big wrong especially wrong"],
["荒谬绝伦","huāng miù jué lún",3,"Absurd beyond all peers.","这种说法荒谬绝伦。","荒唐到了极点。","absurd beyond all peers"],
["荒诞不经","huāng dàn bù jīng",2,"Absurd and bizarre, beyond reason.","他讲的 story 荒诞不经。","不合情理，虚妄离奇。","absurd bizarre not reasonable"],
["莫名其妙","mò míng qí miào",2,"Nobody can name its point — utterly baffling.","他被莫名其妙地骂了一顿。","说不出其中的奥妙，令人不解。","nobody can name it"],
["岂有此理","qǐ yǒu cǐ lǐ",2,"How is this reasonable?!","收取这种费用岂有此理。","哪有这样的道理？","how is this reasonable"],
["忍无可忍","rěn wú kě rěn",2,"Forbearance with no more holding.","他一忍再忍，终于忍无可忍。","忍受到再也无法忍受。","forbearance no can hold"],
["铤而走险","tǐng ér zǒu xiǎn",2,"Desperation walks into danger.","他债台高筑铤而走险。","走投无路时采取冒险行动。","desperate walk into danger"],
["孤注一掷","gū zhù yī zhì",2,"The last stake, one throw — all or nothing.","他孤注一掷投进了全部积蓄。","用尽所有力量冒险一搏。","last stake one throw"],
["狗急跳墙","gǒu jí tiào qiáng",2,"A cornered dog leaps the wall — desperate measures follow.","把他逼急了会狗急跳墙的。","走投无路时不择行动。","dog desperate leaps wall"],
["垂死挣扎","chuí sǐ zhēng zhá",2,"A dying struggle, flailing on.","被困的敌人还在垂死挣扎。","临死前的最后挣扎。","dying struggle flailing on"],
["负隅顽抗","fù yú wán kàng",3,"Cornered in the nook, stubbornly resisting.","嫌犯负隅顽抗被当场制服。","凭借险要地势顽固抵抗。","cornered nook stubborn resist"],
["恼羞成怒","nǎo xiū chéng nù",2,"Vexed, ashamed — turned into rage.","被拆穿后他恼羞成怒。","因恼恨羞愧而发怒。","vexed ashamed become rage"],
["大动肝火","dà dòng gān huǒ",2,"Greatly stirs the liver fire.","一句话让他大动肝火。","大发脾气。","greatly stir liver fire"],
["暴跳如雷","bào tiào rú léi",2,"Leaping violently like thunder.","听到消息他暴跳如雷。","跳脚怒吼，像打雷一样。","violently jumping like thunder"],
["大发雷霆","dà fā léi tíng",2,"Issues a grand thunderbolt of rage.","经理为这事大发雷霆。","大发脾气，高声斥责。","issue grand thunder rage"],
["勃然大怒","bó rán dà nù",2,"Suddenly bursts into fury.","看到结果他勃然大怒。","突然变脸大发脾气。","suddenly burst into fury"],
["气急败坏","qì jí bài huài",2,"Gasping, frantic, rattled, wrecked.","他气急败坏地摔门而去。","上气不接下气，狼狈不堪。","gasping frantic rattled wrecked"],
["面红耳赤","miàn hóng ěr chì",2,"Face red, ears crimson — the debate got physical in color.","两人吵得面红耳赤。","形容争辩或激动得脸色发红。","face red ears crimson"],
["各执一词","gè zhí yī cí",2,"Each side holds its own version.","双方各执一词，互不相让。","各自坚持各自的说法。","each holds its version"],
["互不相让","hù bù xiāng ràng",2,"Neither yields to the other.","谈判桌上双方互不相让。","互不退让。","neither yields to other"],
["剑拔弩张","jiàn bá nǔ zhāng",2,"Swords drawn, bows taut — the tension before the clash.","谈判桌上的气氛剑拔弩张。","形势紧张，一触即发。","swords drawn bows taut"],
["一触即发","yī chù jí fā",1,"One touch and it fires.","局势紧张到一触即发。","形势非常紧迫。","one touch instantly fires"],
["大打出手","dà dǎ chū shǒu",2,"Grandly throws blows about.","话不投机双方大打出手。","凶狠地动手打人。","grandly throw blows about"],
["反目成仇","fǎn mù chéng chóu",2,"Turned faces, become enemies.","昔日好友反目成仇。","翻脸而变成仇敌。","turned faces become enemies"],
["恩断义绝","ēn duàn yì jué",3,"Kindness severed, loyalty ended.","两家人从此恩断义绝。","感情破裂，情义断绝。","kindness severed loyalty ended"],
["势不两立","shì bù liǎng lì",3,"Two sides that cannot coexist.","正义与邪恶势不两立。","双方敌对，不能并存。","two sides cannot coexist"],
["你死我活","nǐ sǐ wǒ huó",3,"You die, I live — no middle ground.","两家价格战打到你死我活。","斗争你死我活，非常激烈。","you die I live"]
];

mergeBulk(BULK_ARGUE19, "argue");
