/* Quiz expansion 3: +50 praise scenes */
const QUIZ_PRAISE_1 = [
  { zh: "他给灾区捐款从来不留名字。", en: "He donates to disaster relief every time — never leaves a name.",
    answer: "乐善好施", mode: "praise", explain: "Giving generously without seeking recognition is 乐善好施." },
  { zh: "他修桥铺路二十年，村里人都敬他。", en: "Twenty years of building bridges and roads; the whole village looks up to him.",
    answer: "行侠仗义", mode: "praise", explain: "Using years of effort and resources to benefit the community reflects 行侠仗义." },
  { zh: "她替被欺负的同事出头，据理力争。", en: "She stood up for the bullied coworker and argued the case to the end.",
    answer: "仗义执言", mode: "praise", explain: "Speaking up on behalf of someone being mistreated is 仗义执言." },
  { zh: "他当组长后第一件事是给每人调到了合适的岗位。", en: "First act as team lead: moving every member into the role that fits them.",
    answer: "知人善任", mode: "praise", explain: "Recognizing each person's strengths and assigning the right role is 知人善任." },
  { zh: "老爷子九十四岁还在院子里种菜，眼不花手不抖。", en: "Ninety-four years old, still gardening — sharp eyes, steady hands.",
    answer: "老当益壮", mode: "praise", explain: "Remaining vigorous and capable at ninety-four is 老当益壮." },
  { zh: "他七十岁开始学钢琴，三年后开了独奏会。", en: "He started piano at seventy; three years later he held a solo recital.",
    answer: "老骥伏枥", mode: "praise", explain: "Beginning an ambitious pursuit at seventy shows 老骥伏枥." },
  { zh: "他把失败项目的每个坑都整理成了内部文档。", en: "He documented every pitfall of the failed project into internal guides for everyone.",
    answer: "高风亮节", mode: "praise", explain: "Turning a personal failure into shared knowledge shows admirable character — 高风亮节." },
  { zh: "她一个人把三百人的年会策划得井井有条。", en: "She single-handedly organized the 300-person annual gala, flawlessly.",
    answer: "独当一面", mode: "praise", explain: "Managing a major event independently and successfully is 独当一面." },
  { zh: "他每天五点起床背单词，雷打不动。", en: "He rises at five daily to memorize vocabulary. Unshakeable.",
    answer: "持之以恒", mode: "praise", explain: "Maintaining the same demanding study habit every day is 持之以恒." },
  { zh: "评委刚说完题目，她已经给出了三种解法。", en: "The judge finished reading the problem; she already had three different solutions.",
    answer: "才思敏捷", mode: "praise", explain: "Producing several solutions almost immediately demonstrates 才思敏捷." },
  { zh: "他随口一提的建议，后来成了公司核心业务。", en: "His casual suggestion later became the company's core business line.",
    answer: "远见卓识", mode: "praise", explain: "Seeing the potential of what later becomes a core business reflects 远见卓识." },
  { zh: "业主群里谁家有纠纷，都请他去主持公道。", en: "Any dispute in the building group chat — they all ask him to arbitrate.",
    answer: "明辨是非", mode: "praise", explain: "Being trusted to judge disputes fairly shows an ability to 明辨是非." },
  { zh: "他把客户没提的需求都提前想到了。", en: "He anticipated requirements the client hadn't even mentioned yet.",
    answer: "深思熟虑", mode: "sarcasm", explain: "Anticipating even unstated requirements shows that the plan was 深思熟虑." },
  { zh: "他拒绝父公司的安排，自己去偏远山区支教。", en: "He turned down the family arrangement and went to teach in a remote mountain village.",
    answer: "胸怀大志", mode: "praise", explain: "Choosing difficult public service over an easy arrangement reflects 胸怀大志." },
  { zh: "火锅店里他先给每个人的碗里下了第一筷子菜。", en: "At hotpot, he serves the first piece of food into everyone else's bowl first.",
    answer: "体贴入微", mode: "sarcasm", explain: "Noticing and serving everyone before himself is 体贴入微." },
  { zh: "婆婆住院，她白天上班晚上陪护，毫无怨言。", en: "Mother-in-law hospitalized: she worked days, kept night vigil, never a word of complaint.",
    answer: "任劳任怨", mode: "praise", explain: "Bearing exhausting work and caregiving without complaint is 任劳任怨." },
  { zh: "他为搭档的错误当众道歉，把功劳都让了出去。", en: "He publicly apologized for his partner's error and gave away all the credit.",
    answer: "顾全大局", mode: "praise", explain: "Absorbing blame and yielding credit to protect the partnership is 顾全大局." },
  { zh: "丈夫失业那年，她说：『正好我想歇歇，你做饭。』", en: "The year he lost his job, she said: 'Perfect, I need a break. You cook.'",
    answer: "相濡以沫", mode: "praise", explain: "Supporting a spouse through hardship with dignity and humor is 相濡以沫." },
  { zh: "他们结婚四十年，还每天手牵手散步。", en: "Forty years married, and they still hold hands on every walk.",
    answer: "白头偕老", mode: "praise", explain: "Four decades of enduring affection embodies 白头偕老." },
  { zh: "答错了他主动认，答对了他说运气好。", en: "Wrong answers: he owns them. Right answers: 'just luck'.",
    answer: "谦虚谨慎", mode: "sarcasm", explain: "Owning errors while minimizing personal credit shows 谦虚谨慎." },
  { zh: "他把客户投诉整理成手册，新员工人手一册。", en: "He turned customer complaints into a handbook that every new hire receives.",
    answer: "化险为夷", mode: "praise", explain: "Converting complaints into preventive training turns risk into advantage — 化险为夷." },
  { zh: "对手公司来挖人，核心团队一个都没走。", en: "The rival company tried poaching; not one core member left.",
    answer: "同心同德", mode: "praise", explain: "The entire core team remaining united under pressure is 同心同德." },
  { zh: "他给流浪猫搭了三个窝，还做了登记表。", en: "He built three shelters for stray cats — with a registration spreadsheet.",
    answer: "心地善良", mode: "praise", explain: "Carefully providing shelter for stray animals reveals 心地善良." },
  { zh: "直播中设备全崩了，他清唱救场，观众暴涨。", en: "All equipment died mid-stream; he sang a cappella and his audience doubled.",
    answer: "随机应变", mode: "praise", explain: "Adapting instantly when every device fails is 随机应变." },
  { zh: "她说到做到，答应的十个承诺兑现了十个。", en: "She promised ten things this year. She delivered ten things.",
    answer: "言而有信", mode: "praise", explain: "Fulfilling every promise exactly as made is 言而有信." },
  { zh: "两位创始人一个懂技术一个懂市场，配合无间。", en: "One founder gets tech, the other gets markets — perfect interlock.",
    answer: "珠联璧合", mode: "praise", explain: "Two complementary strengths working in perfect partnership are 珠联璧合." },
  { zh: "他失败七次，第八次的产品成了爆款。", en: "Seven failures; the eighth product went viral.",
    answer: "百折不挠", mode: "praise", explain: "Continuing after seven failures until success is 百折不挠." },
  { zh: "他当众指出了老板的错误，全场倒吸凉气。", en: "He pointed out the boss's mistake in front of everyone. The room inhaled.",
    answer: "刚正不阿", mode: "praise", explain: "Correcting even the boss publicly for the sake of truth is 刚正不阿." },
];
QUIZ_BANK.push(...QUIZ_PRAISE_1);
